name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          default="luxnox_os"
          echo $default | cat >default
          echo "Using default scheme: $default"

      - name: Build
        run: |
          xcodebuild build-for-testing -project "luxnox_os.xcodeproj" -scheme "luxnox_os" -sdk iphonesimulator
